INSERT INTO accompany.dbo.QAContents (category_id,language_id,question,answer,sort_order,created_at,updated_at,is_deleted) VALUES
	 (7,1,N'1. 什麼是多元陪伴照顧服務？',N'A：為回應民眾「臨短急」服務需求，包括長輩「臨」時有狀況卻找不到服務人力、外籍家庭看護空窗期的「短」期需要服務人力、家人手術或病後需要「急」性後期服務等，勞動部推動「多元陪伴服務服務試辦計畫」，由依法設立滿五年之財團法人或非營利社團法人申請，並通過公益性、專業度與合理收費等評選標準後成為試辦服務單位，聘僱及培訓本國籍及外國籍多元陪伴服務服務工作者到申請服務家庭，提供短期、臨時或持續一定時間之基本日常生活服務、陪同外出、陪同就醫、安全陪伴等全額自費之多元陪伴照顧服務，以減輕家庭照顧負擔。',0,'2025-04-20 07:05:09.31','2025-04-20 07:05:09.31',0),
	 (13,1,N'1. 多元陪伴照顧服務計畫受任私立就業服務資格為何? 更換仲介需再重新核定嗎?',N'<p>A: 試辦單位經本部評選核定後，得委任從事跨國人力仲介業務之私立就業服務機構，辦理外國籍陪伴照顧服務工作者之招募、引進、聘僱管理、生活服務、住宿安排及管理等就業服務事宜。</p><p>&nbsp;</p><p>受委任之私立就業服務機構應符合下列資格：</p><ul>
        <li>申請日前五年內，評鑑成績依規定均屬於 A 級或績優免評鑑者。</li>
        <li>於申請日前二年內，受雇主委任引進或聘僱之看護工及家庭幫傭外國人，佔該機構當年總引進或聘僱外國人人數二分之一以上。</li>
        <li>申請日前二年內，無違反就業服務法相關法規之紀錄。</li>
    </ul><p>&nbsp;</p><p>若試辦單位與私立就業服務機構終止或解除委任關係，得另委任符合前述規定資格之私立就業服務機構辦理相關就業服務業務，並於另行委任後之一個月內，向本部申請核定變更。</p>',0,'2025-04-20 10:52:19.63','2025-04-20 10:52:19.63',0),
	 (12,1,N'1. 如要應聘為陪伴照顧服務工作者，需具備何種資格?',N'<p>A：依審查標準第8條規定略以，外國人受聘僱從事多元陪伴照顧服務工作，其年齡須20歲以上，且入國工作前，應經衛生福利部認可之外國健康檢查醫院或其本國勞工部門指定之訓練單位訓練合格，或在我國境內從事相同工作滿6個月以上者。又所謂相同工作，係指從事家庭幫傭、家庭看護或機構看護之工作。</p><p>&nbsp;</p>',0,'2025-04-20 10:54:06.577','2025-04-20 10:54:06.577',0),
	 (11,1,N'1. 本計畫之目的為何？',N'<p>A：勞動部推動「多元陪伴照顧服務試辦計畫」之目的在於回應民眾「臨短急」服務需求，包括長輩「臨」時有狀況卻找不到服務人力、外籍家庭看護空窗期的「短」期需要服務人力、家人手術或病後需要「急」性後期服務等情況，由依法設立滿五年之財團法人或非營利社團法人申請，並通過公益性、專業度與合理收費等評選標準後成為試辦服務單位，聘僱及培訓本國籍及外國籍多元陪伴照顧服務工作者到申請服務家庭，提供短期、臨時或持續一定時間之基本日常生活服務、陪同外出、陪同就醫、安全陪伴等全額自費之多元陪伴照顧服務，以減輕家庭服務負擔。</p><p>&nbsp;</p>',0,'2025-04-20 10:54:46.783','2025-04-20 10:54:46.783',0),
	 (12,2,N'1. A job as a companion care service worker, what qualifications do I need?',N'<p>A: According to the provisions of Article 8 of the review standards, foreigners who are employed in multi-companion care services must be over 20 years old, and before entering the country to work, they must obtain a foreign health examination from a hospital recognized by the Ministry of Health and Welfare or their own national labor force. Those who have passed a qualification training program at a training unit designated by the department, or have been engaged in the same job within the territory of Taiwan for more than 6 months. The so-called "same job" refers to the work of domestic helpers, home caregivers, or institutional caregivers.</p><p>&nbsp;</p>',0,'2025-04-20 10:56:39.613','2025-04-20 10:56:39.613',0),
	 (12,3,N'1. Việc làm nhân viên dịch vụ chăm sóc đồng hành, tôi cần có những chuyên môn gì?',N'<p>Trả lời: Theo quy định tại Điều 8 của tiêu chuẩn xét duyệt, người nước ngoài làm việc dịch vụ chăm sóc đồng hành đa dạng phải trên 20 tuổi. Trước khi vào nước làm việc, phải có bệnh viện khám sức khỏe nước ngoài được Bộ Y tế công nhận và Phúc lợi hoặc lực lượng lao động quốc gia của họ đã vượt qua khóa đào tạo tại đơn vị đào tạo chỉ định. Hoặc đã làm công việc tương tự ở Đài Loan trong hơn 6 tháng. "Công việc tương tự" dùng để chỉ công việc của người giúp việc gia đình, người chăm sóc tại nhà hoặc người chăm sóc tại cơ quan.</p><p>&nbsp;</p>',0,'2025-04-20 12:47:25.223','2025-04-20 12:47:25.223',0),
	 (12,5,N'1. Pekerjaan sebagai Layanan multiguna perawatan pendamping pekerja asing, kualifikasi apa yang saya perlukan？',N'<p>A : Menurut ketentuan Pasal 8 Undang–undang standar peninjauan, orang asing yang dipekerjakan di beberapa layanan multiguna perawatan pendamping harus berusia di atas 20 tahun, dan sebelum memasuki ke negara tersebut untuk bekerja, mereka harus mendapatkan pemeriksaan kesehatan asing di rumah sakit yang diakui oleh Kementerian Kesehatan dan Kesejahteraan atau Depnaker setempat yang telah lulus pelatihan di unit pelatihan yang ditunjuk oleh departemen, atau telah melakukan pekerjaan yang sama di Taiwan lebih dari 6 bulan lamanya. Atau pekerjaan pada sektor yang sama, yang mengacu pada pekerjaan perawat Tata Laksana Rumah Tangga, perawat Orang Sakit, atau perawat Panti Jompo.</p><p>&nbsp;</p>',0,'2025-04-20 13:38:23.913','2025-04-20 13:38:23.913',0),
	 (12,4,N'1. หากต้องการสมัครเป็นผู้ดูแลต้องมีคุณสมบัติอะไรบ้าง',N'<p>ตอบ: ตามหลักเกณฑ์การพิจารณาบทบัญญัติมาตรา 8 ชาวต่างชาติผู้ที่ถูกจ้างงานบริการดูแลและให้ความช่วยเหลือแบบหลากหลายจะต้องมีอายุมากกว่า 20 ปี และก่อนเข้ามาทำงานในประเทศ ควรผ่านการตรวจสุขภาพจากโรงพยาบาลในต่างประเทศที่ได้รับการรับรองจากกระทรวงสาธารณสุขและสวัสดิการ หรือผ่านการฝึกอบรมจากหน่วยงานที่กระทรวงแรงงานของประเทศต้นทางกำหนด หรือเคยทำงานเดียวกันในประเทศไต้หวันมานานกว่า 6 เดือน และ "งานเดียวกัน" ในที่นี้หมายถึงงาน แม่บ้าน ผู้ดูแลที่บ้าน หรือผู้ดูแลในสถาพยาบาล</p><p>&nbsp;</p>',0,'2025-04-20 13:39:02.64','2025-04-20 13:39:02.64',0),
	 (7,1,N'test',N'test',1,'2025-04-21 15:46:26.093','2025-04-29 01:39:22.23',1),
	 (15,1,N'test',N'test',1,'2025-04-21 15:47:40.94','2025-04-26 11:45:17.323',1);
INSERT INTO accompany.dbo.QAContents (category_id,language_id,question,answer,sort_order,created_at,updated_at,is_deleted) VALUES
	 (15,1,N'123',N'123',0,'2025-04-26 11:43:23.79','2025-04-26 11:45:02.277',1),
	 (7,1,N'test',N'test',1,'2025-04-29 01:39:15.643','2025-04-29 01:39:19.543',1);
