
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BackToTop': typeof import("../components/back-to-top.vue")['default']
    'BlockFeatureOne': typeof import("../components/block-feature/block-feature-one.vue")['default']
    'BlockFeatureThree': typeof import("../components/block-feature/block-feature-three.vue")['default']
    'BlockFeatureTwo': typeof import("../components/block-feature/block-feature-two.vue")['default']
    'BlogAreaTwo': typeof import("../components/blog/blog-area-two.vue")['default']
    'BlogListArea': typeof import("../components/blog/blog-list-area.vue")['default']
    'BreadcrumbOne': typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
    'BreadcrumbTwo': typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
    'ErrMsg': typeof import("../components/err-msg.vue")['default']
    'FancyBannerSix': typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
    'FancyBannerThree': typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
    'FaqAreaOne': typeof import("../components/faq/faq-area-one.vue")['default']
    'FaqAreaThree': typeof import("../components/faq/faq-area-three.vue")['default']
    'FeedbackFour': typeof import("../components/feedback/feedback-four.vue")['default']
    'FeedbackTwo': typeof import("../components/feedback/feedback-two.vue")['default']
    'FooterOne': typeof import("../components/footer/footer-one.vue")['default']
    'FooterTwo': typeof import("../components/footer/footer-two.vue")['default']
    'HeaderNavMenus': typeof import("../components/header/header-nav-menus.vue")['default']
    'HeaderOne': typeof import("../components/header/header-one.vue")['default']
    'HeaderTwo': typeof import("../components/header/header-two.vue")['default']
    'HeroBannerOne': typeof import("../components/hero-banner/hero-banner-one.vue")['default']
    'NewsletterOne': typeof import("../components/newsletter/newsletter-one.vue")['default']
    'Pagination': typeof import("../components/pagination.vue")['default']
    'ServiceDetailsArea': typeof import("../components/service/service-details-area.vue")['default']
    'ServiceV1Area': typeof import("../components/service/service-v1-area.vue")['default']
    'ServiceV2Area': typeof import("../components/service/service-v2-area.vue")['default']
    'TeamOneArea': typeof import("../components/team/team-one-area.vue")['default']
    'TextFeatureOne': typeof import("../components/text-feature/text-feature-one.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBackToTop': typeof import("../components/back-to-top.vue")['default']
    'LazyBlockFeatureOne': typeof import("../components/block-feature/block-feature-one.vue")['default']
    'LazyBlockFeatureThree': typeof import("../components/block-feature/block-feature-three.vue")['default']
    'LazyBlockFeatureTwo': typeof import("../components/block-feature/block-feature-two.vue")['default']
    'LazyBlogAreaTwo': typeof import("../components/blog/blog-area-two.vue")['default']
    'LazyBlogListArea': typeof import("../components/blog/blog-list-area.vue")['default']
    'LazyBreadcrumbOne': typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
    'LazyBreadcrumbTwo': typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
    'LazyErrMsg': typeof import("../components/err-msg.vue")['default']
    'LazyFancyBannerSix': typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
    'LazyFancyBannerThree': typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
    'LazyFaqAreaOne': typeof import("../components/faq/faq-area-one.vue")['default']
    'LazyFaqAreaThree': typeof import("../components/faq/faq-area-three.vue")['default']
    'LazyFeedbackFour': typeof import("../components/feedback/feedback-four.vue")['default']
    'LazyFeedbackTwo': typeof import("../components/feedback/feedback-two.vue")['default']
    'LazyFooterOne': typeof import("../components/footer/footer-one.vue")['default']
    'LazyFooterTwo': typeof import("../components/footer/footer-two.vue")['default']
    'LazyHeaderNavMenus': typeof import("../components/header/header-nav-menus.vue")['default']
    'LazyHeaderOne': typeof import("../components/header/header-one.vue")['default']
    'LazyHeaderTwo': typeof import("../components/header/header-two.vue")['default']
    'LazyHeroBannerOne': typeof import("../components/hero-banner/hero-banner-one.vue")['default']
    'LazyNewsletterOne': typeof import("../components/newsletter/newsletter-one.vue")['default']
    'LazyPagination': typeof import("../components/pagination.vue")['default']
    'LazyServiceDetailsArea': typeof import("../components/service/service-details-area.vue")['default']
    'LazyServiceV1Area': typeof import("../components/service/service-v1-area.vue")['default']
    'LazyServiceV2Area': typeof import("../components/service/service-v2-area.vue")['default']
    'LazyTeamOneArea': typeof import("../components/team/team-one-area.vue")['default']
    'LazyTextFeatureOne': typeof import("../components/text-feature/text-feature-one.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BackToTop: typeof import("../components/back-to-top.vue")['default']
export const BlockFeatureOne: typeof import("../components/block-feature/block-feature-one.vue")['default']
export const BlockFeatureThree: typeof import("../components/block-feature/block-feature-three.vue")['default']
export const BlockFeatureTwo: typeof import("../components/block-feature/block-feature-two.vue")['default']
export const BlogAreaTwo: typeof import("../components/blog/blog-area-two.vue")['default']
export const BlogListArea: typeof import("../components/blog/blog-list-area.vue")['default']
export const BreadcrumbOne: typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
export const BreadcrumbTwo: typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
export const ErrMsg: typeof import("../components/err-msg.vue")['default']
export const FancyBannerSix: typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
export const FancyBannerThree: typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
export const FaqAreaOne: typeof import("../components/faq/faq-area-one.vue")['default']
export const FaqAreaThree: typeof import("../components/faq/faq-area-three.vue")['default']
export const FeedbackFour: typeof import("../components/feedback/feedback-four.vue")['default']
export const FeedbackTwo: typeof import("../components/feedback/feedback-two.vue")['default']
export const FooterOne: typeof import("../components/footer/footer-one.vue")['default']
export const FooterTwo: typeof import("../components/footer/footer-two.vue")['default']
export const HeaderNavMenus: typeof import("../components/header/header-nav-menus.vue")['default']
export const HeaderOne: typeof import("../components/header/header-one.vue")['default']
export const HeaderTwo: typeof import("../components/header/header-two.vue")['default']
export const HeroBannerOne: typeof import("../components/hero-banner/hero-banner-one.vue")['default']
export const NewsletterOne: typeof import("../components/newsletter/newsletter-one.vue")['default']
export const Pagination: typeof import("../components/pagination.vue")['default']
export const ServiceDetailsArea: typeof import("../components/service/service-details-area.vue")['default']
export const ServiceV1Area: typeof import("../components/service/service-v1-area.vue")['default']
export const ServiceV2Area: typeof import("../components/service/service-v2-area.vue")['default']
export const TeamOneArea: typeof import("../components/team/team-one-area.vue")['default']
export const TextFeatureOne: typeof import("../components/text-feature/text-feature-one.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBackToTop: typeof import("../components/back-to-top.vue")['default']
export const LazyBlockFeatureOne: typeof import("../components/block-feature/block-feature-one.vue")['default']
export const LazyBlockFeatureThree: typeof import("../components/block-feature/block-feature-three.vue")['default']
export const LazyBlockFeatureTwo: typeof import("../components/block-feature/block-feature-two.vue")['default']
export const LazyBlogAreaTwo: typeof import("../components/blog/blog-area-two.vue")['default']
export const LazyBlogListArea: typeof import("../components/blog/blog-list-area.vue")['default']
export const LazyBreadcrumbOne: typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
export const LazyBreadcrumbTwo: typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
export const LazyErrMsg: typeof import("../components/err-msg.vue")['default']
export const LazyFancyBannerSix: typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
export const LazyFancyBannerThree: typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
export const LazyFaqAreaOne: typeof import("../components/faq/faq-area-one.vue")['default']
export const LazyFaqAreaThree: typeof import("../components/faq/faq-area-three.vue")['default']
export const LazyFeedbackFour: typeof import("../components/feedback/feedback-four.vue")['default']
export const LazyFeedbackTwo: typeof import("../components/feedback/feedback-two.vue")['default']
export const LazyFooterOne: typeof import("../components/footer/footer-one.vue")['default']
export const LazyFooterTwo: typeof import("../components/footer/footer-two.vue")['default']
export const LazyHeaderNavMenus: typeof import("../components/header/header-nav-menus.vue")['default']
export const LazyHeaderOne: typeof import("../components/header/header-one.vue")['default']
export const LazyHeaderTwo: typeof import("../components/header/header-two.vue")['default']
export const LazyHeroBannerOne: typeof import("../components/hero-banner/hero-banner-one.vue")['default']
export const LazyNewsletterOne: typeof import("../components/newsletter/newsletter-one.vue")['default']
export const LazyPagination: typeof import("../components/pagination.vue")['default']
export const LazyServiceDetailsArea: typeof import("../components/service/service-details-area.vue")['default']
export const LazyServiceV1Area: typeof import("../components/service/service-v1-area.vue")['default']
export const LazyServiceV2Area: typeof import("../components/service/service-v2-area.vue")['default']
export const LazyTeamOneArea: typeof import("../components/team/team-one-area.vue")['default']
export const LazyTextFeatureOne: typeof import("../components/text-feature/text-feature-one.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
