
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutJoinUs': typeof import("../components/about/about-join-us.vue")['default']
    'AboutPurposeArea': typeof import("../components/about/about-purpose-area.vue")['default']
    'AboutUsTwoArea': typeof import("../components/about/about-us-two-area.vue")['default']
    'BackToTop': typeof import("../components/back-to-top.vue")['default']
    'BlockFeatureIndex': typeof import("../components/block-feature/block-feature-index.vue")['default']
    'BlockFeatureThree': typeof import("../components/block-feature/block-feature-three.vue")['default']
    'BlockFeatureTwo': typeof import("../components/block-feature/block-feature-two.vue")['default']
    'BlogAreaIndex': typeof import("../components/blog/blog-area-index.vue")['default']
    'BlogListArea': typeof import("../components/blog/blog-list-area.vue")['default']
    'BreadcrumbOne': typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
    'BreadcrumbTwo': typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
    'ErrMsg': typeof import("../components/err-msg.vue")['default']
    'FancyBannerSix': typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
    'FancyBannerThree': typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
    'FaqAreaIndex': typeof import("../components/faq/faq-area-index.vue")['default']
    'FaqAreaThree': typeof import("../components/faq/faq-area-three.vue")['default']
    'FaqItem': typeof import("../components/faq/faq-item.vue")['default']
    'FeedbackFour': typeof import("../components/feedback/feedback-four.vue")['default']
    'FeedbackTwo': typeof import("../components/feedback/feedback-two.vue")['default']
    'FooterOne': typeof import("../components/footer/footer-one.vue")['default']
    'FooterTwo': typeof import("../components/footer/footer-two.vue")['default']
    'HeaderNavMenus': typeof import("../components/header/header-nav-menus.vue")['default']
    'HeaderOne': typeof import("../components/header/header-one.vue")['default']
    'HeaderTwo': typeof import("../components/header/header-two.vue")['default']
    'HeroBannerIndex': typeof import("../components/hero-banner/hero-banner-index.vue")['default']
    'NewsletterOne': typeof import("../components/newsletter/newsletter-one.vue")['default']
    'Pagination': typeof import("../components/pagination.vue")['default']
    'PortfolioOne': typeof import("../components/portfolio/portfolio-one.vue")['default']
    'PortfolioSingle': typeof import("../components/portfolio/portfolio-single.vue")['default']
    'PortfolioTwo': typeof import("../components/portfolio/portfolio-two.vue")['default']
    'ProjectDetailsProcess': typeof import("../components/project/details/project-details-process.vue")['default']
    'ProjectDetailsV1Area': typeof import("../components/project/details/project-details-v1-area.vue")['default']
    'ProjectDetailsV2Area': typeof import("../components/project/details/project-details-v2-area.vue")['default']
    'ProjectV1Area': typeof import("../components/project/project-v1-area.vue")['default']
    'ProjectV2Area': typeof import("../components/project/project-v2-area.vue")['default']
    'ProjectV3Area': typeof import("../components/project/project-v3-area.vue")['default']
    'ServiceArea': typeof import("../components/service/service-area.vue")['default']
    'ServiceDetailsArea': typeof import("../components/service/service-details-area.vue")['default']
    'ServicePurposeArea': typeof import("../components/service/service-purpose-area.vue")['default']
    'ServiceV2Area': typeof import("../components/service/service-v2-area.vue")['default']
    'TeamAreaFive': typeof import("../components/team/team-area-five.vue")['default']
    'TeamAreaFour': typeof import("../components/team/team-area-four.vue")['default']
    'TeamOneArea': typeof import("../components/team/team-one-area.vue")['default']
    'TeamSingleTwo': typeof import("../components/team/team-single-two.vue")['default']
    'TeamSingle': typeof import("../components/team/team-single.vue")['default']
    'TextFeatureIndex': typeof import("../components/text-feature/text-feature-index.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutJoinUs': typeof import("../components/about/about-join-us.vue")['default']
    'LazyAboutPurposeArea': typeof import("../components/about/about-purpose-area.vue")['default']
    'LazyAboutUsTwoArea': typeof import("../components/about/about-us-two-area.vue")['default']
    'LazyBackToTop': typeof import("../components/back-to-top.vue")['default']
    'LazyBlockFeatureIndex': typeof import("../components/block-feature/block-feature-index.vue")['default']
    'LazyBlockFeatureThree': typeof import("../components/block-feature/block-feature-three.vue")['default']
    'LazyBlockFeatureTwo': typeof import("../components/block-feature/block-feature-two.vue")['default']
    'LazyBlogAreaIndex': typeof import("../components/blog/blog-area-index.vue")['default']
    'LazyBlogListArea': typeof import("../components/blog/blog-list-area.vue")['default']
    'LazyBreadcrumbOne': typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
    'LazyBreadcrumbTwo': typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
    'LazyErrMsg': typeof import("../components/err-msg.vue")['default']
    'LazyFancyBannerSix': typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
    'LazyFancyBannerThree': typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
    'LazyFaqAreaIndex': typeof import("../components/faq/faq-area-index.vue")['default']
    'LazyFaqAreaThree': typeof import("../components/faq/faq-area-three.vue")['default']
    'LazyFaqItem': typeof import("../components/faq/faq-item.vue")['default']
    'LazyFeedbackFour': typeof import("../components/feedback/feedback-four.vue")['default']
    'LazyFeedbackTwo': typeof import("../components/feedback/feedback-two.vue")['default']
    'LazyFooterOne': typeof import("../components/footer/footer-one.vue")['default']
    'LazyFooterTwo': typeof import("../components/footer/footer-two.vue")['default']
    'LazyHeaderNavMenus': typeof import("../components/header/header-nav-menus.vue")['default']
    'LazyHeaderOne': typeof import("../components/header/header-one.vue")['default']
    'LazyHeaderTwo': typeof import("../components/header/header-two.vue")['default']
    'LazyHeroBannerIndex': typeof import("../components/hero-banner/hero-banner-index.vue")['default']
    'LazyNewsletterOne': typeof import("../components/newsletter/newsletter-one.vue")['default']
    'LazyPagination': typeof import("../components/pagination.vue")['default']
    'LazyPortfolioOne': typeof import("../components/portfolio/portfolio-one.vue")['default']
    'LazyPortfolioSingle': typeof import("../components/portfolio/portfolio-single.vue")['default']
    'LazyPortfolioTwo': typeof import("../components/portfolio/portfolio-two.vue")['default']
    'LazyProjectDetailsProcess': typeof import("../components/project/details/project-details-process.vue")['default']
    'LazyProjectDetailsV1Area': typeof import("../components/project/details/project-details-v1-area.vue")['default']
    'LazyProjectDetailsV2Area': typeof import("../components/project/details/project-details-v2-area.vue")['default']
    'LazyProjectV1Area': typeof import("../components/project/project-v1-area.vue")['default']
    'LazyProjectV2Area': typeof import("../components/project/project-v2-area.vue")['default']
    'LazyProjectV3Area': typeof import("../components/project/project-v3-area.vue")['default']
    'LazyServiceArea': typeof import("../components/service/service-area.vue")['default']
    'LazyServiceDetailsArea': typeof import("../components/service/service-details-area.vue")['default']
    'LazyServicePurposeArea': typeof import("../components/service/service-purpose-area.vue")['default']
    'LazyServiceV2Area': typeof import("../components/service/service-v2-area.vue")['default']
    'LazyTeamAreaFive': typeof import("../components/team/team-area-five.vue")['default']
    'LazyTeamAreaFour': typeof import("../components/team/team-area-four.vue")['default']
    'LazyTeamOneArea': typeof import("../components/team/team-one-area.vue")['default']
    'LazyTeamSingleTwo': typeof import("../components/team/team-single-two.vue")['default']
    'LazyTeamSingle': typeof import("../components/team/team-single.vue")['default']
    'LazyTextFeatureIndex': typeof import("../components/text-feature/text-feature-index.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutJoinUs: typeof import("../components/about/about-join-us.vue")['default']
export const AboutPurposeArea: typeof import("../components/about/about-purpose-area.vue")['default']
export const AboutUsTwoArea: typeof import("../components/about/about-us-two-area.vue")['default']
export const BackToTop: typeof import("../components/back-to-top.vue")['default']
export const BlockFeatureIndex: typeof import("../components/block-feature/block-feature-index.vue")['default']
export const BlockFeatureThree: typeof import("../components/block-feature/block-feature-three.vue")['default']
export const BlockFeatureTwo: typeof import("../components/block-feature/block-feature-two.vue")['default']
export const BlogAreaIndex: typeof import("../components/blog/blog-area-index.vue")['default']
export const BlogListArea: typeof import("../components/blog/blog-list-area.vue")['default']
export const BreadcrumbOne: typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
export const BreadcrumbTwo: typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
export const ErrMsg: typeof import("../components/err-msg.vue")['default']
export const FancyBannerSix: typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
export const FancyBannerThree: typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
export const FaqAreaIndex: typeof import("../components/faq/faq-area-index.vue")['default']
export const FaqAreaThree: typeof import("../components/faq/faq-area-three.vue")['default']
export const FaqItem: typeof import("../components/faq/faq-item.vue")['default']
export const FeedbackFour: typeof import("../components/feedback/feedback-four.vue")['default']
export const FeedbackTwo: typeof import("../components/feedback/feedback-two.vue")['default']
export const FooterOne: typeof import("../components/footer/footer-one.vue")['default']
export const FooterTwo: typeof import("../components/footer/footer-two.vue")['default']
export const HeaderNavMenus: typeof import("../components/header/header-nav-menus.vue")['default']
export const HeaderOne: typeof import("../components/header/header-one.vue")['default']
export const HeaderTwo: typeof import("../components/header/header-two.vue")['default']
export const HeroBannerIndex: typeof import("../components/hero-banner/hero-banner-index.vue")['default']
export const NewsletterOne: typeof import("../components/newsletter/newsletter-one.vue")['default']
export const Pagination: typeof import("../components/pagination.vue")['default']
export const PortfolioOne: typeof import("../components/portfolio/portfolio-one.vue")['default']
export const PortfolioSingle: typeof import("../components/portfolio/portfolio-single.vue")['default']
export const PortfolioTwo: typeof import("../components/portfolio/portfolio-two.vue")['default']
export const ProjectDetailsProcess: typeof import("../components/project/details/project-details-process.vue")['default']
export const ProjectDetailsV1Area: typeof import("../components/project/details/project-details-v1-area.vue")['default']
export const ProjectDetailsV2Area: typeof import("../components/project/details/project-details-v2-area.vue")['default']
export const ProjectV1Area: typeof import("../components/project/project-v1-area.vue")['default']
export const ProjectV2Area: typeof import("../components/project/project-v2-area.vue")['default']
export const ProjectV3Area: typeof import("../components/project/project-v3-area.vue")['default']
export const ServiceArea: typeof import("../components/service/service-area.vue")['default']
export const ServiceDetailsArea: typeof import("../components/service/service-details-area.vue")['default']
export const ServicePurposeArea: typeof import("../components/service/service-purpose-area.vue")['default']
export const ServiceV2Area: typeof import("../components/service/service-v2-area.vue")['default']
export const TeamAreaFive: typeof import("../components/team/team-area-five.vue")['default']
export const TeamAreaFour: typeof import("../components/team/team-area-four.vue")['default']
export const TeamOneArea: typeof import("../components/team/team-one-area.vue")['default']
export const TeamSingleTwo: typeof import("../components/team/team-single-two.vue")['default']
export const TeamSingle: typeof import("../components/team/team-single.vue")['default']
export const TextFeatureIndex: typeof import("../components/text-feature/text-feature-index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutJoinUs: typeof import("../components/about/about-join-us.vue")['default']
export const LazyAboutPurposeArea: typeof import("../components/about/about-purpose-area.vue")['default']
export const LazyAboutUsTwoArea: typeof import("../components/about/about-us-two-area.vue")['default']
export const LazyBackToTop: typeof import("../components/back-to-top.vue")['default']
export const LazyBlockFeatureIndex: typeof import("../components/block-feature/block-feature-index.vue")['default']
export const LazyBlockFeatureThree: typeof import("../components/block-feature/block-feature-three.vue")['default']
export const LazyBlockFeatureTwo: typeof import("../components/block-feature/block-feature-two.vue")['default']
export const LazyBlogAreaIndex: typeof import("../components/blog/blog-area-index.vue")['default']
export const LazyBlogListArea: typeof import("../components/blog/blog-list-area.vue")['default']
export const LazyBreadcrumbOne: typeof import("../components/breadcrumb/breadcrumb-one.vue")['default']
export const LazyBreadcrumbTwo: typeof import("../components/breadcrumb/breadcrumb-two.vue")['default']
export const LazyErrMsg: typeof import("../components/err-msg.vue")['default']
export const LazyFancyBannerSix: typeof import("../components/fancy-banner/fancy-banner-six.vue")['default']
export const LazyFancyBannerThree: typeof import("../components/fancy-banner/fancy-banner-three.vue")['default']
export const LazyFaqAreaIndex: typeof import("../components/faq/faq-area-index.vue")['default']
export const LazyFaqAreaThree: typeof import("../components/faq/faq-area-three.vue")['default']
export const LazyFaqItem: typeof import("../components/faq/faq-item.vue")['default']
export const LazyFeedbackFour: typeof import("../components/feedback/feedback-four.vue")['default']
export const LazyFeedbackTwo: typeof import("../components/feedback/feedback-two.vue")['default']
export const LazyFooterOne: typeof import("../components/footer/footer-one.vue")['default']
export const LazyFooterTwo: typeof import("../components/footer/footer-two.vue")['default']
export const LazyHeaderNavMenus: typeof import("../components/header/header-nav-menus.vue")['default']
export const LazyHeaderOne: typeof import("../components/header/header-one.vue")['default']
export const LazyHeaderTwo: typeof import("../components/header/header-two.vue")['default']
export const LazyHeroBannerIndex: typeof import("../components/hero-banner/hero-banner-index.vue")['default']
export const LazyNewsletterOne: typeof import("../components/newsletter/newsletter-one.vue")['default']
export const LazyPagination: typeof import("../components/pagination.vue")['default']
export const LazyPortfolioOne: typeof import("../components/portfolio/portfolio-one.vue")['default']
export const LazyPortfolioSingle: typeof import("../components/portfolio/portfolio-single.vue")['default']
export const LazyPortfolioTwo: typeof import("../components/portfolio/portfolio-two.vue")['default']
export const LazyProjectDetailsProcess: typeof import("../components/project/details/project-details-process.vue")['default']
export const LazyProjectDetailsV1Area: typeof import("../components/project/details/project-details-v1-area.vue")['default']
export const LazyProjectDetailsV2Area: typeof import("../components/project/details/project-details-v2-area.vue")['default']
export const LazyProjectV1Area: typeof import("../components/project/project-v1-area.vue")['default']
export const LazyProjectV2Area: typeof import("../components/project/project-v2-area.vue")['default']
export const LazyProjectV3Area: typeof import("../components/project/project-v3-area.vue")['default']
export const LazyServiceArea: typeof import("../components/service/service-area.vue")['default']
export const LazyServiceDetailsArea: typeof import("../components/service/service-details-area.vue")['default']
export const LazyServicePurposeArea: typeof import("../components/service/service-purpose-area.vue")['default']
export const LazyServiceV2Area: typeof import("../components/service/service-v2-area.vue")['default']
export const LazyTeamAreaFive: typeof import("../components/team/team-area-five.vue")['default']
export const LazyTeamAreaFour: typeof import("../components/team/team-area-four.vue")['default']
export const LazyTeamOneArea: typeof import("../components/team/team-one-area.vue")['default']
export const LazyTeamSingleTwo: typeof import("../components/team/team-single-two.vue")['default']
export const LazyTeamSingle: typeof import("../components/team/team-single.vue")['default']
export const LazyTextFeatureIndex: typeof import("../components/text-feature/text-feature-index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
